export const ACTION_GET_POSTS_STARTED = "GET_POSTS_STARTED";
export const ACTION_GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const ACTION_GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const ACTION_GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const ACTION_GET_POST_BY_ID_FAILURE = "GET_POST_BY_ID_FAILURE";
export const ACTION_GET_POST_BY_ID_STARTED = "GET_POST_BY_ID_STARTED";

export const ACTION_CREATE_POST_STARTED = "CREATE_POST_STARTED";
export const ACTION_CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const ACTION_LOGIN_USER = 'LOGIN_USER';
export const ACTION_FAIL_USER = 'FAIL_USER';
export const ACTION_LOGOUT_USER = 'LOGOUT_USER';
